### PR TITLE
"Fixed" skip comments in DefinitionProvider, rearranged some code and…

### PR DESCRIPTION
**Pull request by HAG87**
… added comments. Adapted the code of DefinitionProvider class to vscode-maxscript

### CODE REVIEW

**Comment by usakhelo** [comment]
Hi @HAG87,
Thanks a lot for the PR. I wrote that thing quite a while ago, so on new vscode my version doesn't even run. Your commit makes it work and it's great.

**Comment by usakhelo** [comment]
One thing I noticed is that if some symbol is found inside the comment block it is ignored.
Here's the example code. If you try the extension on it you'll see that `Main_Functions` struct and `OnLoad_button` are not listed in the symbols:
```
(
  struct Helper_Funcs
  (
  )

  struct Main_Functions
  (
  )

  (
    fn onLoad_button sender args =
    (
    )

    fn onMaterialMaskClick sender args =
    (
      --Main_Functions.fill_ui_elements presets
    )
   
    --fn onLoad_button sender args =
  )
)
```

**Comment by HAG87** [comment]
screen shot 06-08-18 at 10 29 pm

Tested it, got "Go to Symbol" working. "Go to Definition" is disabled in comments because of:
```
            let lineText = document.lineAt(position.line).text;
            let lineTillCurrentPosition = lineText.substr(0, position.character);
            if (lineTillCurrentPosition.includes('--')) { reject(null); }
```

**Comment by usakhelo** [comment]
Yes, it's working! For some reason I couldn't compile it correctly but now it works.
Now it's working on my version with your PR, but still doesn't on your extension, am I right? It would be great if it worked on your extension since my version requires other maxscript extension to be installed.

Thanks! Merging this...

**Comment by HAG87** [comment]
I got it working, but having some errors that don't let me publish the
extension, triying to figure it out. Also, added some config settings, so
you can disable the languaje features on my extension and play around with
yours.

**Comment by HAG87** [comment]
Settings:
```
  "maxscript.completions": true,
  "maxscript.gotosymbol": true,
  "maxscript.gotodefinition": true,
```

**Pull request merged**
